[package]
name = "wendy"
version = "0.1.0"
authors = ["Joe Becher <me@drazisil.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
grcov = "0.5.15"