name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    defaults:
      run:
        working-directory: daemon
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Coverage setup
      run: |
        export CARGO_INCREMENTAL=0
        export RUSTFLAGS="-Zprofile -Ccodegen-units=1 -Copt-level=0 -Clink-dead-code -Coverflow-checks=off -Zpanic_abort_tests -Cpanic=abort"
        export RUSTDOCFLAGS="-Cpanic=abort"
        rustup default nightly
        cargo install grcov
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Generate coverage report
      run: grcov ./target/debug/ -s . -t lcov --llvm --branch --ignore-not-existing -o ./target/debug/coverage.lcov
    - name: Codecov
      uses: codecov/codecov-action@v1.0.13
      with:
        name: daemon
        directory: daemon
        flags: daemon
